pool:
  vmImage: ubuntu-latest
stages:
- stage: ci
  displayName: Continuous Integration
  jobs:
  - job: build
    displayName: Build Project Assets
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: |
        dotnet publish \
        --configuration Release \
        --output out \
        --self-contained \
        --runtime win-x64 \
        -p:EnableCompressionInSingleFile=true \
        -p:PublishSingleFile=true \
        -p:PublishReadyToRun=true \
        -p: DibugType=embedded
      displayName: publish .NET console project

